PGPASSWORD=$KOLIBRI_DATABASE_PASSWORD pg_restore -U $KOLIBRI_DATABASE_USER -h $KOLIBRI_DATABASE_HOST -p $KOLIBRI_DATABASE_PORT -d $KOLIBRI_DATABASE_NAME <backup file>


PGPASSWORD=$KOLIBRI_DATABASE_PASSWORD pg_restore -U $KOLIBRI_DATABASE_USER -h $KOLIBRI_DATABASE_HOST -p $KOLIBRI_DATABASE_PORT -C -d $KOLIBRI_DATABASE_NAME <backup file>
